package pl.adrian.pieper.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import pl.adrian.pieper.rtf.sample.PlaceHolderProcessor;
import pl.adrian.pieper.rtf.sample.ProcessorModule;
import pl.adrian.pieper.rtf.sample.TemplatesManager;
import pl.adrian.pieper.rtf.sample.TempleteModel;

/**
 *
 * @author Adi
 */
public class MainPanel extends javax.swing.JPanel implements ProcessorModule.Gui{
    private TempleteModel template;
    private TemplatesManager templatesManager = new TemplatesManager();
    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        try{
            templatesManager.load("templates");
            setTemplate(templatesManager.getTemplates().get(0));
            templatesComboBox.setModel(new DefaultComboBoxModel(templatesManager.getTemplates().toArray()));
            templatesComboBox.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent ae) {
                    setTemplate((TempleteModel) templatesComboBox.getSelectedItem());
                }
            });
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        templatesComboBox = new javax.swing.JComboBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        placeHoldersPanel = new pl.adrian.pieper.gui.OtherDatePanel();
        tablePanel1 = new pl.adrian.pieper.gui.TablePanel();
        processButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("<html>POMIARY OKRESOWE INSTALACJI ELEKTRYCZNEJ </html>");
        jLabel1.setMinimumSize(new java.awt.Dimension(320, 96));
        jLabel1.setPreferredSize(new java.awt.Dimension(320, 96));
        add(jLabel1, new java.awt.GridBagConstraints());

        templatesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(templatesComboBox, gridBagConstraints);

        jScrollPane1.setViewportView(placeHoldersPanel);

        jTabbedPane1.addTab("Inne dane", jScrollPane1);

        tablePanel1.setPreferredSize(null);
        jTabbedPane1.addTab("Wyniki", tablePanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jTabbedPane1, gridBagConstraints);

        processButton.setText("OK");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        add(processButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        template.process();
    }//GEN-LAST:event_processButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private pl.adrian.pieper.gui.OtherDatePanel placeHoldersPanel;
    private javax.swing.JButton processButton;
    private pl.adrian.pieper.gui.TablePanel tablePanel1;
    private javax.swing.JComboBox templatesComboBox;
    // End of variables declaration//GEN-END:variables

    private void setTemplate(TempleteModel templeteModel) {
        this.template = templeteModel;
        for (ProcessorModule module : templeteModel.getModules()) {
            module.attach(this);
        }
    }

    @Override
    public void attach(PlaceHolderProcessor holderProcessor) {
        placeHoldersPanel.setData(holderProcessor);
    }
}
