/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.adrian.pieper.gui;

/**
 *
 * @author Adi
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        documentModel = new pl.adrian.pieper.rtf.sample.DocumentModel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        otherDatePanel1 = new pl.adrian.pieper.gui.OtherDatePanel();
        tablePanel1 = new pl.adrian.pieper.gui.TablePanel();
        processButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("<html>POMIARY OKRESOWE INSTALACJI ELEKTRYCZNEJ </html>");
        jLabel1.setMinimumSize(new java.awt.Dimension(320, 96));
        jLabel1.setPreferredSize(new java.awt.Dimension(320, 96));
        add(jLabel1, new java.awt.GridBagConstraints());

        otherDatePanel1.setData(documentModel);
        jScrollPane1.setViewportView(otherDatePanel1);

        jTabbedPane1.addTab("Inne dane", jScrollPane1);

        tablePanel1.setPreferredSize(null);
        jTabbedPane1.addTab("Wyniki", tablePanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jTabbedPane1, gridBagConstraints);

        processButton.setText("OK");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        add(processButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        
        documentModel.process();
    }//GEN-LAST:event_processButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pl.adrian.pieper.rtf.sample.DocumentModel documentModel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private pl.adrian.pieper.gui.OtherDatePanel otherDatePanel1;
    private javax.swing.JButton processButton;
    private pl.adrian.pieper.gui.TablePanel tablePanel1;
    // End of variables declaration//GEN-END:variables
}
