/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.adrian.pieper.gui;

import pl.adrian.pieper.domain.TemplatesManager;

/**
 *
 * @author Adi
 */
public class MainFrame extends javax.swing.JFrame {

    public MainFrame(TemplatesManager templatesManager) {
        initComponents();
        mainPanel1.setTemplatesManager(templatesManager);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel1 = new pl.adrian.pieper.gui.MainPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(mainPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pl.adrian.pieper.gui.MainPanel mainPanel1;
    // End of variables declaration//GEN-END:variables
}
