/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.adrian.pieper.gui;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import org.apache.batik.ext.swing.GridBagConstants;
import pl.adrian.pieper.rtf.sample.DocumentModel;
import pl.adrian.pieper.rtf.sample.SimpleData;

/**
 *
 * @author Adi
 */
public class OtherDatePanel extends javax.swing.JPanel {

    /**
     * Creates new form OtherDatePanel
     */
    public OtherDatePanel() {
        initComponents();
    }
    
    public void setData(DocumentModel documentModel){
        for (SimpleData placeHolder : documentModel.getPlaceHolders().values()) {
            System.out.println(placeHolder.getPlaceholder());
            SingleDataView singleDataView = new SingleDataView();
            singleDataView.setData(placeHolder);
            GridBagConstraints bagConstants = new GridBagConstraints();
            bagConstants.gridx = 0;
            bagConstants.gridy = GridBagConstraints.RELATIVE;
            bagConstants.fill = GridBagConstraints.BOTH;
            bagConstants.weightx = 1.0;
            add(singleDataView, bagConstants);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
