/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.adrian.pieper.gui;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import pl.adrian.pieper.domain.PlaceHolder;

/**
 *
 * @author Adi
 */
public class SingleDataView extends javax.swing.JPanel {

    /**
     * Creates new form SingleData
     */
    public SingleDataView() {
        initComponents();
    }

    public void setValueName(String name){
        label.setText(name);
    }
    
    public void setValue(String string){
        field.setText(string);
    }
    
    public String getValue(){
        return field.getText();
    }
    
    public void setData(final PlaceHolder data){
        label.setText(data.getName());
        field.setText(data.getValue());
        field.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
            }

            @Override
            public void focusLost(FocusEvent e) {
                data.setValue(field.getText());
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField1 = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        field = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setMaximumSize(new java.awt.Dimension(10000, 10000));
        setMinimumSize(new java.awt.Dimension(360, 64));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(360, 64));
        setLayout(new java.awt.GridBagLayout());

        label.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(label, gridBagConstraints);

        field.setText("jTextField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(field, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField field;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
